# goal : path - sequence of 2D points
geometry_msgs/Pose2D[] pose
#geometry_msgs/Pose2D pose
---
# result
bool result
---
# feedback : percentage of the distance traveled by the turtle
float32 progress